title: "CS G523 Embedded Project"
description: "Event-driven, safety-critical embedded system"
remote_theme: bamr87/zer0-mistakes
markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
